### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by ericfont** [bbbradsmith/nsfplay#1]
I use your nsfplay quite a lot through wine on linux.  I think it would be great to run natively.  I'm be willing to try porting to QT so gui is cross platform, and maybe use port audio or some other cross platform audio api.  I think then it would also hopefully work on Mac or any other OS, including possibly android (which latest QT supports), if done correctly.

**Comment by bbbradsmith** [comment]
I have plans to make NSFPlay a lot more portable than it currently is.

The primary thing that prohibits porting to other platforms at the moment  is a dependency on MFC.

The intention is to restructure the program so that the sound and player stuff is all separate from the UI and everything else, and rebuild the player GUI from scratch in a more portable way (most likely with wxWidgets), so that the GUI will be easily portable to PC/Mac/Linux etc., and platforms requiring something special can just build their own thing that interfaces with the player/sound layer directly.

I expect I will be able to spend time on this a few months from now.
